---
apiVersion: v1
kind: Namespace
metadata:
  name: core-cilium
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bootstrap
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: bootstrap
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-operator-values
  namespace: kube-system
data:
  values.yaml: |
    fullnameOverride: core-flux-operator
    resources:
      limits:
        cpu: 100m
        memory: 350Mi
      requests:
        cpu: 100m
        memory: 350Mi
    web:
      enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-values
  namespace: kube-system
data:
  values.yaml: |
    cluster:
      name: test-cluster
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK 
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
          enabled: false
      hostRoot: /sys/fs/cgroup
    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true
    k8sServiceHost: 192.168.8.192
    k8sServicePort: 6443
    kubeProxyReplacement: true
    hostFirewall:
      enabled: false
    hubble:
      enabled: false
    externalIPs:
      enabled: true
    nodePort:
      enabled: true
      addresses: 192.168.8.0/24
    loadBalancer:
      algorithm: maglev
    ipam:
      mode: kubernetes
    routingMode: native
    ipv4NativeRoutingCIDR:  10.244.0.0/16
    enableIPv4Masquerade: true
    autoDirectNodeRoutes: true
    bpf:
      masquerade: true
    ipMasqAgent:
      enabled: true
      config:
        nonMasqueradeCIDRs:
          -  10.244.0.0/16
    l2announcements:
      enabled: true
    envoy:
      enabled: false          
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-bootstrap
  namespace: kube-system
spec:
  backoffLimit: 5
  template:
    spec:
      hostNetwork: true
      serviceAccountName: bootstrap
      restartPolicy: OnFailure
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: cilium-values
          configMap:
            name: cilium-values
        - name: flux-operator-values 
          configMap:
            name: flux-operator-values
      containers:
        - name: bootstrap
          image: alpine/k8s:1.35.0
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: cilium-values
              mountPath: /cilium-values
            - name: flux-operator-values
              mountPath: /flux-operator-values
          command:
            - /bin/bash
            - -ceu
            - |
                APISERVER="https://192.168.8.192:6443"
                TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
                CA="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

                cat > /tmp/kubeconfig <<EOF
                apiVersion: v1
                kind: Config
                clusters:
                - name: c
                  cluster:
                    certificate-authority: ${CA}
                    server: ${APISERVER}
                users:
                - name: sa
                  user:
                    token: ${TOKEN}
                contexts:
                - name: ctx
                  context:
                    cluster: c
                    user: sa
                current-context: ctx
                EOF

                export KUBECONFIG=/tmp/kubeconfig
                kubectl get nodes
                echo "==> Installing Cilium"

                helm repo add cilium https://helm.cilium.io
                helm repo update

                helm upgrade --install cilium cilium/cilium \
                  --namespace core-cilium \
                  --create-namespace \
                  --values /cilium-values/values.yaml

                echo "==> Waiting for Cilium"
                kubectl -n core-cilium rollout status ds/cilium --timeout=5m

                echo "==> Installing Fluxcd Operator"
                helm upgrade --install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator \
                  --namespace core-flux-system \
                  --values /flux-operator-values/values.yaml \
                  --create-namespace

                echo "==> Waiting for Fluxcd Operator"
                kubectl -n core-flux-system rollout status deploy/flux-operator --timeout=5m

                echo "==> Installing Flux Instance"
                kubectl apply -f - <<'EOF'
                apiVersion: fluxcd.controlplane.io/v1
                kind: FluxInstance
                metadata:
                  name: flux
                  namespace: core-flux-system
                spec:
                  distribution:
                    version: "2.x"
                    registry: "ghcr.io/fluxcd"
                    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
                  components:
                    - source-controller
                    - kustomize-controller
                    - helm-controller
                    - notification-controller
                    - image-reflector-controller
                    - image-automation-controller
                  cluster:
                    type: kubernetes
                    multitenant: false
                    networkPolicy: true
                    domain: "cluster.local"
                EOF

                echo "==> Waiting for Flux controllers"
                for ctrl in source-controller kustomize-controller helm-controller notification-controller image-reflector-controller image-automation-controller; do
                  kubectl -n core-flux-system rollout status deploy/${ctrl} --timeout=5m
                done

                echo "==> Installing Flux GitRepository + Kustomization (example)"
                kubectl apply -f - <<'EOF'
                apiVersion: source.toolkit.fluxcd.io/v1
                kind: GitRepository
                metadata:
                  name: cluster-gitops
                  namespace: core-flux-system
                spec:
                  interval: 1m
                  url: https://github.com/rodkodanila/talos-bootstrap-repo.git
                  ref:
                    branch: main
                ---
                apiVersion: kustomize.toolkit.fluxcd.io/v1
                kind: Kustomization
                metadata:
                  name: cluster-sync
                  namespace: core-flux-system
                spec:
                  interval: 10m
                  sourceRef:
                    kind: GitRepository
                    name: cluster-gitops
                  path: ./gitops/clusters/test-cluster
                  prune: true
                  wait: true
                  timeout: 5m
                EOF
