apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: core-flux-system
spec:
  interval: 10m
  type: oci
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
