apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: core-flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: flux-operator
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: core-flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    fullnameOverride: core-flux-operator
    resources:
      limits:
        cpu: 100m
        memory: 350Mi
      requests:
        cpu: 100m
        memory: 350Mi
    web:
      enabled: true 